; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?first_loop@@3PEAU_pri_loop_box_@@EA		; first_loop
PUBLIC	?last_loop@@3PEAU_pri_loop_box_@@EA		; last_loop
_BSS	SEGMENT
?first_loop@@3PEAU_pri_loop_box_@@EA DQ 01H DUP (?)	; first_loop
?last_loop@@3PEAU_pri_loop_box_@@EA DQ 01H DUP (?)	; last_loop
_BSS	ENDS
CONST	SEGMENT
$SG3498	DB	'pri_loop', 00H
	ORG $+7
$SG3499	DB	'/dev/pri_loop', 00H
CONST	ENDS
PUBLIC	?pri_loop_init@@YAXXZ				; pri_loop_init
PUBLIC	?pri_put_message@@YAXPEAU_pri_event_@@@Z	; pri_put_message
PUBLIC	?pri_loop_destroy@@YAXPEAU_pri_loop_box_@@@Z	; pri_loop_destroy
PUBLIC	?pri_loop_destroy_by_id@@YAXG@Z			; pri_loop_destroy_by_id
PUBLIC	?pri_loop_create@@YAXXZ				; pri_loop_create
PUBLIC	?pri_get_message@@YAXPEAU_pri_event_@@@Z	; pri_get_message
PUBLIC	?pri_loop_ioquery@@YAHPEAU_vfs_node_@@HPEAX@Z	; pri_loop_ioquery
EXTRN	strcpy:PROC
EXTRN	memset:PROC
EXTRN	memcpy:PROC
EXTRN	AuPmmngrAlloc:PROC
EXTRN	AuPmmngrFree:PROC
EXTRN	x64_cli:PROC
EXTRN	x64_sti:PROC
EXTRN	malloc:PROC
EXTRN	vfs_mount:PROC
EXTRN	?unblock_thread@@YAXPEAU_thread_@@@Z:PROC	; unblock_thread
EXTRN	?get_current_thread@@YAPEAU_thread_@@XZ:PROC	; get_current_thread
EXTRN	?thread_iterate_ready_list@@YAPEAU_thread_@@G@Z:PROC ; thread_iterate_ready_list
EXTRN	?thread_iterate_block_list@@YAPEAU_thread_@@H@Z:PROC ; thread_iterate_block_list
pdata	SEGMENT
$pdata$?pri_loop_init@@YAXXZ DD imagerel $LN3
	DD	imagerel $LN3+195
	DD	imagerel $unwind$?pri_loop_init@@YAXXZ
$pdata$?pri_put_message@@YAXPEAU_pri_event_@@@Z DD imagerel $LN10
	DD	imagerel $LN10+245
	DD	imagerel $unwind$?pri_put_message@@YAXPEAU_pri_event_@@@Z
$pdata$?pri_loop_destroy@@YAXPEAU_pri_loop_box_@@@Z DD imagerel $LN8
	DD	imagerel $LN8+162
	DD	imagerel $unwind$?pri_loop_destroy@@YAXPEAU_pri_loop_box_@@@Z
$pdata$?pri_loop_destroy_by_id@@YAXG@Z DD imagerel $LN7
	DD	imagerel $LN7+82
	DD	imagerel $unwind$?pri_loop_destroy_by_id@@YAXG@Z
$pdata$?pri_loop_create@@YAXXZ DD imagerel $LN5
	DD	imagerel $LN5+200
	DD	imagerel $unwind$?pri_loop_create@@YAXXZ
$pdata$?pri_get_message@@YAXPEAU_pri_event_@@@Z DD imagerel $LN9
	DD	imagerel $LN9+203
	DD	imagerel $unwind$?pri_get_message@@YAXPEAU_pri_event_@@@Z
$pdata$?pri_loop_ioquery@@YAHPEAU_vfs_node_@@HPEAX@Z DD imagerel $LN13
	DD	imagerel $LN13+244
	DD	imagerel $unwind$?pri_loop_ioquery@@YAHPEAU_vfs_node_@@HPEAX@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?pri_loop_init@@YAXXZ DD 010401H
	DD	06204H
$unwind$?pri_put_message@@YAXPEAU_pri_event_@@@Z DD 010901H
	DD	08209H
$unwind$?pri_loop_destroy@@YAXPEAU_pri_loop_box_@@@Z DD 010901H
	DD	04209H
$unwind$?pri_loop_destroy_by_id@@YAXG@Z DD 010901H
	DD	06209H
$unwind$?pri_loop_create@@YAXXZ DD 010401H
	DD	06204H
$unwind$?pri_get_message@@YAXPEAU_pri_event_@@@Z DD 010901H
	DD	06209H
$unwind$?pri_loop_ioquery@@YAHPEAU_vfs_node_@@HPEAX@Z DD 021501H
	DD	01f0115H
xdata	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\xeneva\aurora\aurora\ipc\pri_loop.cpp
_TEXT	SEGMENT
tv64 = 32
box$1 = 40
tv68 = 48
event$2 = 56
e$3 = 64
file$ = 256
code$ = 264
arg$ = 272
?pri_loop_ioquery@@YAHPEAU_vfs_node_@@HPEAX@Z PROC	; pri_loop_ioquery

; 168  : int pri_loop_ioquery (vfs_node_t *file, int code, void *arg) {

$LN13:
	mov	QWORD PTR [rsp+24], r8
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 248				; 000000f8H

; 169  : 	switch (code) {

	mov	eax, DWORD PTR code$[rsp]
	mov	DWORD PTR tv64[rsp], eax
	cmp	DWORD PTR tv64[rsp], 401		; 00000191H
	je	SHORT $LN8@pri_loop_i
	cmp	DWORD PTR tv64[rsp], 402		; 00000192H
	je	SHORT $LN7@pri_loop_i
	cmp	DWORD PTR tv64[rsp], 403		; 00000193H
	je	SHORT $LN2@pri_loop_i
	cmp	DWORD PTR tv64[rsp], 404		; 00000194H
	je	SHORT $LN1@pri_loop_i
	jmp	$LN9@pri_loop_i
$LN8@pri_loop_i:

; 170  : 	case PRI_LOOP_CREATE: {
; 171  : 		pri_loop_create();

	call	?pri_loop_create@@YAXXZ			; pri_loop_create

; 172  : 		break;

	jmp	$LN9@pri_loop_i
$LN7@pri_loop_i:

; 173  : 	}
; 174  : 	case PRI_LOOP_DESTROY: {
; 175  : 		pri_loop_box_t *box;
; 176  : 		for (box = first_loop; box != NULL; box = box->next) {

	mov	rax, QWORD PTR ?first_loop@@3PEAU_pri_loop_box_@@EA ; first_loop
	mov	QWORD PTR box$1[rsp], rax
	jmp	SHORT $LN6@pri_loop_i
$LN5@pri_loop_i:
	mov	rax, QWORD PTR box$1[rsp]
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR box$1[rsp], rax
$LN6@pri_loop_i:
	cmp	QWORD PTR box$1[rsp], 0
	je	SHORT $LN4@pri_loop_i

; 177  : 			if (box->owner_id == get_current_thread()->id) {

	mov	rax, QWORD PTR box$1[rsp]
	movzx	eax, WORD PTR [rax+8]
	mov	DWORD PTR tv68[rsp], eax
	call	?get_current_thread@@YAPEAU_thread_@@XZ	; get_current_thread
	movzx	eax, WORD PTR [rax+738]
	mov	ecx, DWORD PTR tv68[rsp]
	cmp	ecx, eax
	jne	SHORT $LN3@pri_loop_i

; 178  : 				pri_loop_destroy(box);

	mov	rcx, QWORD PTR box$1[rsp]
	call	?pri_loop_destroy@@YAXPEAU_pri_loop_box_@@@Z ; pri_loop_destroy

; 179  : 				break;

	jmp	SHORT $LN4@pri_loop_i
$LN3@pri_loop_i:

; 180  : 			}
; 181  : 		}

	jmp	SHORT $LN5@pri_loop_i
$LN4@pri_loop_i:

; 182  : 		break;

	jmp	SHORT $LN9@pri_loop_i
$LN2@pri_loop_i:

; 183  : 	}
; 184  : 	case PRI_LOOP_PUT_EVENT: {
; 185  : 		pri_event_t *event = (pri_event_t*)arg;

	mov	rax, QWORD PTR arg$[rsp]
	mov	QWORD PTR event$2[rsp], rax

; 186  : 		pri_put_message(event);

	mov	rcx, QWORD PTR event$2[rsp]
	call	?pri_put_message@@YAXPEAU_pri_event_@@@Z ; pri_put_message

; 187  : 		break;

	jmp	SHORT $LN9@pri_loop_i
$LN1@pri_loop_i:

; 188  : 	}
; 189  : 
; 190  : 	case PRI_LOOP_GET_EVENT: {
; 191  : 		pri_event_t e;
; 192  : 		pri_get_message(&e);

	lea	rcx, QWORD PTR e$3[rsp]
	call	?pri_get_message@@YAXPEAU_pri_event_@@@Z ; pri_get_message

; 193  : 		memcpy (arg,&e,sizeof(pri_event_t));

	mov	r8d, 176				; 000000b0H
	lea	rdx, QWORD PTR e$3[rsp]
	mov	rcx, QWORD PTR arg$[rsp]
	call	memcpy
$LN9@pri_loop_i:

; 194  : 		break;
; 195  : 	}
; 196  : 	}
; 197  : 
; 198  : 	return 1;

	mov	eax, 1

; 199  : }

	add	rsp, 248				; 000000f8H
	ret	0
?pri_loop_ioquery@@YAHPEAU_vfs_node_@@HPEAX@Z ENDP	; pri_loop_ioquery
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\xeneva\aurora\aurora\ipc\pri_loop.cpp
_TEXT	SEGMENT
owner_id$ = 32
loop$1 = 40
event$ = 64
?pri_get_message@@YAXPEAU_pri_event_@@@Z PROC		; pri_get_message

; 140  : void pri_get_message (pri_event_t *event) {

$LN9:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 141  : 	x64_cli ();

	call	x64_cli

; 142  : 
; 143  : 	uint16_t owner_id = get_current_thread()->id;

	call	?get_current_thread@@YAPEAU_thread_@@XZ	; get_current_thread
	movzx	eax, WORD PTR [rax+738]
	mov	WORD PTR owner_id$[rsp], ax

; 144  : 	for (pri_loop_box_t *loop = first_loop; loop != NULL; loop = loop->next) {

	mov	rax, QWORD PTR ?first_loop@@3PEAU_pri_loop_box_@@EA ; first_loop
	mov	QWORD PTR loop$1[rsp], rax
	jmp	SHORT $LN6@pri_get_me
$LN5@pri_get_me:
	mov	rax, QWORD PTR loop$1[rsp]
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR loop$1[rsp], rax
$LN6@pri_get_me:
	cmp	QWORD PTR loop$1[rsp], 0
	je	SHORT $LN4@pri_get_me

; 145  : 		if (loop->owner_id == owner_id) {

	mov	rax, QWORD PTR loop$1[rsp]
	movzx	eax, WORD PTR [rax+8]
	movzx	ecx, WORD PTR owner_id$[rsp]
	cmp	eax, ecx
	jne	SHORT $LN3@pri_get_me

; 146  : 			if (loop->message_pending){

	mov	rax, QWORD PTR loop$1[rsp]
	movzx	eax, BYTE PTR [rax+10]
	test	eax, eax
	je	SHORT $LN2@pri_get_me

; 147  : 				memcpy (event,loop->address, sizeof(pri_event_t));

	mov	r8d, 176				; 000000b0H
	mov	rax, QWORD PTR loop$1[rsp]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR event$[rsp]
	call	memcpy

; 148  : 				memset (loop->address, 0, sizeof(pri_event_t));

	mov	r8d, 176				; 000000b0H
	xor	edx, edx
	mov	rax, QWORD PTR loop$1[rsp]
	mov	rcx, QWORD PTR [rax]
	call	memset

; 149  : 				loop->pending_msg_count--;

	mov	rax, QWORD PTR loop$1[rsp]
	movzx	eax, WORD PTR [rax+12]
	dec	ax
	mov	rcx, QWORD PTR loop$1[rsp]
	mov	WORD PTR [rcx+12], ax

; 150  : 				if (loop->pending_msg_count == 0) {

	mov	rax, QWORD PTR loop$1[rsp]
	movzx	eax, WORD PTR [rax+12]
	test	eax, eax
	jne	SHORT $LN1@pri_get_me

; 151  : 					loop->message_pending = false;

	mov	rax, QWORD PTR loop$1[rsp]
	mov	BYTE PTR [rax+10], 0
$LN1@pri_get_me:
$LN2@pri_get_me:

; 152  : 				}
; 153  : 			} 
; 154  : 			break;

	jmp	SHORT $LN4@pri_get_me
$LN3@pri_get_me:

; 155  : 		}
; 156  : 	}

	jmp	$LN5@pri_get_me
$LN4@pri_get_me:

; 157  : 
; 158  : 	x64_sti();

	call	x64_sti

; 159  : 	return;
; 160  : }

	add	rsp, 56					; 00000038H
	ret	0
?pri_get_message@@YAXPEAU_pri_event_@@@Z ENDP		; pri_get_message
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\xeneva\aurora\aurora\ipc\pri_loop.cpp
_TEXT	SEGMENT
loop$ = 32
?pri_loop_create@@YAXXZ PROC				; pri_loop_create

; 44   : void pri_loop_create () {

$LN5:
	sub	rsp, 56					; 00000038H

; 45   : 	pri_loop_box_t *loop = (pri_loop_box_t*)AuPmmngrAlloc();  //malloc(sizeof(pri_loop_box_t));

	call	AuPmmngrAlloc
	mov	QWORD PTR loop$[rsp], rax

; 46   : 	loop->address = AuPmmngrAlloc();//malloc(sizeof(pri_event_t));

	call	AuPmmngrAlloc
	mov	rcx, QWORD PTR loop$[rsp]
	mov	QWORD PTR [rcx], rax

; 47   : 	memset(loop->address,0, sizeof(pri_event_t));

	mov	r8d, 176				; 000000b0H
	xor	edx, edx
	mov	rax, QWORD PTR loop$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	memset

; 48   : 	loop->owner_id = get_current_thread()->id;

	call	?get_current_thread@@YAPEAU_thread_@@XZ	; get_current_thread
	mov	rcx, QWORD PTR loop$[rsp]
	movzx	eax, WORD PTR [rax+738]
	mov	WORD PTR [rcx+8], ax

; 49   : 	loop->pending_msg_count = 0;

	xor	eax, eax
	mov	rcx, QWORD PTR loop$[rsp]
	mov	WORD PTR [rcx+12], ax

; 50   : 	loop->message_pending = 0;

	mov	rax, QWORD PTR loop$[rsp]
	mov	BYTE PTR [rax+10], 0

; 51   : 	loop->next = NULL;

	mov	rax, QWORD PTR loop$[rsp]
	mov	QWORD PTR [rax+16], 0

; 52   : 	loop->prev = NULL;

	mov	rax, QWORD PTR loop$[rsp]
	mov	QWORD PTR [rax+24], 0

; 53   : 
; 54   : 	if (first_loop == NULL)  {

	cmp	QWORD PTR ?first_loop@@3PEAU_pri_loop_box_@@EA, 0 ; first_loop
	jne	SHORT $LN2@pri_loop_c

; 55   : 		first_loop = loop;

	mov	rax, QWORD PTR loop$[rsp]
	mov	QWORD PTR ?first_loop@@3PEAU_pri_loop_box_@@EA, rax ; first_loop

; 56   : 		last_loop = loop;

	mov	rax, QWORD PTR loop$[rsp]
	mov	QWORD PTR ?last_loop@@3PEAU_pri_loop_box_@@EA, rax ; last_loop

; 57   : 	} else {

	jmp	SHORT $LN1@pri_loop_c
$LN2@pri_loop_c:

; 58   : 		last_loop->next = loop;

	mov	rax, QWORD PTR ?last_loop@@3PEAU_pri_loop_box_@@EA ; last_loop
	mov	rcx, QWORD PTR loop$[rsp]
	mov	QWORD PTR [rax+16], rcx

; 59   : 		loop->prev = last_loop;

	mov	rax, QWORD PTR loop$[rsp]
	mov	rcx, QWORD PTR ?last_loop@@3PEAU_pri_loop_box_@@EA ; last_loop
	mov	QWORD PTR [rax+24], rcx

; 60   : 		last_loop = loop;

	mov	rax, QWORD PTR loop$[rsp]
	mov	QWORD PTR ?last_loop@@3PEAU_pri_loop_box_@@EA, rax ; last_loop
$LN1@pri_loop_c:

; 61   : 	}
; 62   : }

	add	rsp, 56					; 00000038H
	ret	0
?pri_loop_create@@YAXXZ ENDP				; pri_loop_create
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\xeneva\aurora\aurora\ipc\pri_loop.cpp
_TEXT	SEGMENT
loop$1 = 32
id$ = 64
?pri_loop_destroy_by_id@@YAXG@Z PROC			; pri_loop_destroy_by_id

; 93   : void pri_loop_destroy_by_id (uint16_t id) {

$LN7:
	mov	WORD PTR [rsp+8], cx
	sub	rsp, 56					; 00000038H

; 94   : 	for (pri_loop_box_t *loop = first_loop; loop != NULL; loop = loop->next) {

	mov	rax, QWORD PTR ?first_loop@@3PEAU_pri_loop_box_@@EA ; first_loop
	mov	QWORD PTR loop$1[rsp], rax
	jmp	SHORT $LN4@pri_loop_d
$LN3@pri_loop_d:
	mov	rax, QWORD PTR loop$1[rsp]
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR loop$1[rsp], rax
$LN4@pri_loop_d:
	cmp	QWORD PTR loop$1[rsp], 0
	je	SHORT $LN2@pri_loop_d

; 95   : 		if (loop->owner_id == id) {

	mov	rax, QWORD PTR loop$1[rsp]
	movzx	eax, WORD PTR [rax+8]
	movzx	ecx, WORD PTR id$[rsp]
	cmp	eax, ecx
	jne	SHORT $LN1@pri_loop_d

; 96   : 			pri_loop_destroy (loop);

	mov	rcx, QWORD PTR loop$1[rsp]
	call	?pri_loop_destroy@@YAXPEAU_pri_loop_box_@@@Z ; pri_loop_destroy

; 97   : 			break;

	jmp	SHORT $LN2@pri_loop_d
$LN1@pri_loop_d:

; 98   : 		}
; 99   : 	}

	jmp	SHORT $LN3@pri_loop_d
$LN2@pri_loop_d:

; 100  : 
; 101  : 	return;
; 102  : }

	add	rsp, 56					; 00000038H
	ret	0
?pri_loop_destroy_by_id@@YAXG@Z ENDP			; pri_loop_destroy_by_id
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\xeneva\aurora\aurora\ipc\pri_loop.cpp
_TEXT	SEGMENT
box$ = 48
?pri_loop_destroy@@YAXPEAU_pri_loop_box_@@@Z PROC	; pri_loop_destroy

; 68   : void pri_loop_destroy (pri_loop_box_t *box) {

$LN8:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H

; 69   : 	if (first_loop == NULL)

	cmp	QWORD PTR ?first_loop@@3PEAU_pri_loop_box_@@EA, 0 ; first_loop
	jne	SHORT $LN5@pri_loop_d

; 70   : 		return;

	jmp	$LN6@pri_loop_d
$LN5@pri_loop_d:

; 71   : 
; 72   : 	if (box == first_loop) {

	mov	rax, QWORD PTR ?first_loop@@3PEAU_pri_loop_box_@@EA ; first_loop
	cmp	QWORD PTR box$[rsp], rax
	jne	SHORT $LN4@pri_loop_d

; 73   : 		first_loop = first_loop->next;

	mov	rax, QWORD PTR ?first_loop@@3PEAU_pri_loop_box_@@EA ; first_loop
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR ?first_loop@@3PEAU_pri_loop_box_@@EA, rax ; first_loop

; 74   : 	} else {

	jmp	SHORT $LN3@pri_loop_d
$LN4@pri_loop_d:

; 75   : 		box->prev->next = box->next;

	mov	rax, QWORD PTR box$[rsp]
	mov	rax, QWORD PTR [rax+24]
	mov	rcx, QWORD PTR box$[rsp]
	mov	rcx, QWORD PTR [rcx+16]
	mov	QWORD PTR [rax+16], rcx
$LN3@pri_loop_d:

; 76   : 	}
; 77   : 
; 78   : 	if (box == last_loop) {

	mov	rax, QWORD PTR ?last_loop@@3PEAU_pri_loop_box_@@EA ; last_loop
	cmp	QWORD PTR box$[rsp], rax
	jne	SHORT $LN2@pri_loop_d

; 79   : 		last_loop = box->prev;

	mov	rax, QWORD PTR box$[rsp]
	mov	rax, QWORD PTR [rax+24]
	mov	QWORD PTR ?last_loop@@3PEAU_pri_loop_box_@@EA, rax ; last_loop

; 80   : 	} else {

	jmp	SHORT $LN1@pri_loop_d
$LN2@pri_loop_d:

; 81   : 		box->next->prev = box->prev;

	mov	rax, QWORD PTR box$[rsp]
	mov	rax, QWORD PTR [rax+16]
	mov	rcx, QWORD PTR box$[rsp]
	mov	rcx, QWORD PTR [rcx+24]
	mov	QWORD PTR [rax+24], rcx
$LN1@pri_loop_d:

; 82   : 	}
; 83   : 
; 84   : 	AuPmmngrFree(box->address);

	mov	rax, QWORD PTR box$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	AuPmmngrFree

; 85   : 	AuPmmngrFree(box);

	mov	rcx, QWORD PTR box$[rsp]
	call	AuPmmngrFree
$LN6@pri_loop_d:

; 86   : 	
; 87   : }

	add	rsp, 40					; 00000028H
	ret	0
?pri_loop_destroy@@YAXPEAU_pri_loop_box_@@@Z ENDP	; pri_loop_destroy
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\xeneva\aurora\aurora\ipc\pri_loop.cpp
_TEXT	SEGMENT
hunged$ = 32
owner_id$ = 36
loop$1 = 40
thread$ = 48
event$ = 80
?pri_put_message@@YAXPEAU_pri_event_@@@Z PROC		; pri_put_message

; 108  : void pri_put_message (pri_event_t *event) {

$LN10:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 109  : 	x64_cli();

	call	x64_cli

; 110  : 	bool hunged = false;

	mov	BYTE PTR hunged$[rsp], 0

; 111  : 	uint16_t owner_id = event->to_id;

	mov	rax, QWORD PTR event$[rsp]
	movzx	eax, BYTE PTR [rax+1]
	mov	WORD PTR owner_id$[rsp], ax

; 112  : 	for (pri_loop_box_t *loop = first_loop; loop != NULL; loop = loop->next) {

	mov	rax, QWORD PTR ?first_loop@@3PEAU_pri_loop_box_@@EA ; first_loop
	mov	QWORD PTR loop$1[rsp], rax
	jmp	SHORT $LN7@pri_put_me
$LN6@pri_put_me:
	mov	rax, QWORD PTR loop$1[rsp]
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR loop$1[rsp], rax
$LN7@pri_put_me:
	cmp	QWORD PTR loop$1[rsp], 0
	je	SHORT $LN5@pri_put_me

; 113  : 		if (loop->owner_id == owner_id) {

	mov	rax, QWORD PTR loop$1[rsp]
	movzx	eax, WORD PTR [rax+8]
	movzx	ecx, WORD PTR owner_id$[rsp]
	cmp	eax, ecx
	jne	SHORT $LN4@pri_put_me

; 114  : 			if (loop->message_pending)

	mov	rax, QWORD PTR loop$1[rsp]
	movzx	eax, BYTE PTR [rax+10]
	test	eax, eax
	je	SHORT $LN3@pri_put_me

; 115  : 				break;

	jmp	SHORT $LN5@pri_put_me
$LN3@pri_put_me:

; 116  : 			memcpy (loop->address, event, sizeof(pri_event_t));

	mov	r8d, 176				; 000000b0H
	mov	rdx, QWORD PTR event$[rsp]
	mov	rax, QWORD PTR loop$1[rsp]
	mov	rcx, QWORD PTR [rax]
	call	memcpy

; 117  : 			loop->message_pending = 1;

	mov	rax, QWORD PTR loop$1[rsp]
	mov	BYTE PTR [rax+10], 1

; 118  : 			loop->pending_msg_count++;

	mov	rax, QWORD PTR loop$1[rsp]
	movzx	eax, WORD PTR [rax+12]
	inc	ax
	mov	rcx, QWORD PTR loop$1[rsp]
	mov	WORD PTR [rcx+12], ax

; 119  : 			break;

	jmp	SHORT $LN5@pri_put_me
$LN4@pri_put_me:

; 120  : 		}
; 121  : 	}

	jmp	SHORT $LN6@pri_put_me
$LN5@pri_put_me:

; 122  : 
; 123  : 	//! check if the destination thread is blocked or not
; 124  : 	//! if blocked, wake it up, cause new message is pending
; 125  : 	thread_t *thread = thread_iterate_ready_list(owner_id);	

	movzx	ecx, WORD PTR owner_id$[rsp]
	call	?thread_iterate_ready_list@@YAPEAU_thread_@@G@Z ; thread_iterate_ready_list
	mov	QWORD PTR thread$[rsp], rax

; 126  : 	if (thread == NULL) 

	cmp	QWORD PTR thread$[rsp], 0
	jne	SHORT $LN2@pri_put_me

; 127  : 		thread = thread_iterate_block_list(owner_id);

	movzx	eax, WORD PTR owner_id$[rsp]
	mov	ecx, eax
	call	?thread_iterate_block_list@@YAPEAU_thread_@@H@Z ; thread_iterate_block_list
	mov	QWORD PTR thread$[rsp], rax
$LN2@pri_put_me:

; 128  : 	if (thread != NULL && thread->state == THREAD_STATE_BLOCKED) {

	cmp	QWORD PTR thread$[rsp], 0
	je	SHORT $LN1@pri_put_me
	mov	rax, QWORD PTR thread$[rsp]
	movzx	eax, BYTE PTR [rax+736]
	cmp	eax, 3
	jne	SHORT $LN1@pri_put_me

; 129  : 		unblock_thread(thread);

	mov	rcx, QWORD PTR thread$[rsp]
	call	?unblock_thread@@YAXPEAU_thread_@@@Z	; unblock_thread
$LN1@pri_put_me:
$ret$11:

; 130  : 	}
; 131  : ret:
; 132  : 	x64_sti();

	call	x64_sti

; 133  : 	return;
; 134  : }

	add	rsp, 72					; 00000048H
	ret	0
?pri_put_message@@YAXPEAU_pri_event_@@@Z ENDP		; pri_put_message
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\xeneva\aurora\aurora\ipc\pri_loop.cpp
_TEXT	SEGMENT
node$ = 32
?pri_loop_init@@YAXXZ PROC				; pri_loop_init

; 204  : void pri_loop_init () {

$LN3:
	sub	rsp, 56					; 00000038H

; 205  : 	vfs_node_t *node = (vfs_node_t*)malloc(sizeof(vfs_node_t));

	mov	ecx, 104				; 00000068H
	call	malloc
	mov	QWORD PTR node$[rsp], rax

; 206  : 	strcpy (node->filename, "pri_loop");

	mov	rax, QWORD PTR node$[rsp]
	lea	rdx, OFFSET FLAT:$SG3498
	mov	rcx, rax
	call	strcpy

; 207  : 	node->size = 0;

	mov	rax, QWORD PTR node$[rsp]
	mov	DWORD PTR [rax+32], 0

; 208  : 	node->eof = 0;

	mov	rax, QWORD PTR node$[rsp]
	mov	BYTE PTR [rax+36], 0

; 209  : 	node->pos = 0;

	mov	rax, QWORD PTR node$[rsp]
	mov	DWORD PTR [rax+40], 0

; 210  : 	node->current = 0;

	mov	rax, QWORD PTR node$[rsp]
	mov	DWORD PTR [rax+44], 0

; 211  : 	node->flags = FS_FLAG_GENERAL;

	mov	rax, QWORD PTR node$[rsp]
	mov	BYTE PTR [rax+48], 2

; 212  : 	node->status = 0;

	mov	rax, QWORD PTR node$[rsp]
	mov	BYTE PTR [rax+49], 0

; 213  : 	node->open = 0;

	mov	rax, QWORD PTR node$[rsp]
	mov	QWORD PTR [rax+64], 0

; 214  : 	node->read = 0;

	mov	rax, QWORD PTR node$[rsp]
	mov	QWORD PTR [rax+72], 0

; 215  : 	node->write = 0;

	mov	rax, QWORD PTR node$[rsp]
	mov	QWORD PTR [rax+80], 0

; 216  : 	node->read_blk = 0;

	mov	rax, QWORD PTR node$[rsp]
	mov	QWORD PTR [rax+88], 0

; 217  : 	node->ioquery = pri_loop_ioquery;

	mov	rax, QWORD PTR node$[rsp]
	lea	rcx, OFFSET FLAT:?pri_loop_ioquery@@YAHPEAU_vfs_node_@@HPEAX@Z ; pri_loop_ioquery
	mov	QWORD PTR [rax+96], rcx

; 218  : 	vfs_mount ("/dev/pri_loop", node, 0);

	xor	r8d, r8d
	mov	rdx, QWORD PTR node$[rsp]
	lea	rcx, OFFSET FLAT:$SG3499
	call	vfs_mount

; 219  : }

	add	rsp, 56					; 00000038H
	ret	0
?pri_loop_init@@YAXXZ ENDP				; pri_loop_init
_TEXT	ENDS
END
