; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG3802	DB	'dev', 00H
$SG3820	DB	'/', 00H
CONST	ENDS
PUBLIC	?sys_open_file@@YAHPEADPEAU_file_@@@Z		; sys_open_file
PUBLIC	?sys_read_file@@YAXHPEAEPEAU_file_@@@Z		; sys_read_file
PUBLIC	?sys_write_file@@YAXHPEAEPEAU_file_@@@Z		; sys_write_file
EXTRN	strcmp:PROC
EXTRN	strchr:PROC
EXTRN	memset:PROC
EXTRN	memcpy:PROC
EXTRN	?vfs_finddir@@YAPEAU_vfs_node_@@PEAD@Z:PROC	; vfs_finddir
EXTRN	openfs:PROC
EXTRN	readfs:PROC
EXTRN	writefs:PROC
EXTRN	readfs_block:PROC
EXTRN	x64_cli:PROC
EXTRN	AuPmmngrAlloc:PROC
EXTRN	AuPmmngrFree:PROC
EXTRN	p2v:PROC
EXTRN	v2p:PROC
EXTRN	malloc:PROC
EXTRN	get_current_thread:PROC
pdata	SEGMENT
$pdata$?sys_open_file@@YAHPEADPEAU_file_@@@Z DD imagerel $LN18
	DD	imagerel $LN18+762
	DD	imagerel $unwind$?sys_open_file@@YAHPEADPEAU_file_@@@Z
$pdata$?sys_read_file@@YAXHPEAEPEAU_file_@@@Z DD imagerel $LN12
	DD	imagerel $LN12+363
	DD	imagerel $unwind$?sys_read_file@@YAXHPEAEPEAU_file_@@@Z
$pdata$?sys_write_file@@YAXHPEAEPEAU_file_@@@Z DD imagerel $LN6
	DD	imagerel $LN6+289
	DD	imagerel $unwind$?sys_write_file@@YAXHPEAEPEAU_file_@@@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?sys_open_file@@YAHPEADPEAU_file_@@@Z DD 041301H
	DD	0390113H
	DD	0600b700cH
$unwind$?sys_read_file@@YAXHPEAEPEAU_file_@@@Z DD 011201H
	DD	08212H
$unwind$?sys_write_file@@YAXHPEAEPEAU_file_@@@Z DD 021501H
	DD	0150115H
xdata	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\xeneva\aurora\aurora\sysserv\sysfile.cpp
_TEXT	SEGMENT
node$ = 32
file$ = 48
fd$ = 176
buffer$ = 184
ufile$ = 192
?sys_write_file@@YAXHPEAEPEAU_file_@@@Z PROC		; sys_write_file

; 160  : void sys_write_file (int fd, unsigned char* buffer, FILE *ufile) {

$LN6:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 168				; 000000a8H

; 161  : 	x64_cli();

	call	x64_cli

; 162  : 	vfs_node_t file;
; 163  : 	file.size = ufile->size;

	mov	rax, QWORD PTR ufile$[rsp]
	mov	eax, DWORD PTR [rax+4]
	mov	DWORD PTR file$[rsp+32], eax

; 164  : 	file.eof = ufile->eof;

	mov	rax, QWORD PTR ufile$[rsp]
	movzx	eax, BYTE PTR [rax+8]
	mov	BYTE PTR file$[rsp+36], al

; 165  : 	file.pos = ufile->pos;

	mov	rax, QWORD PTR ufile$[rsp]
	mov	eax, DWORD PTR [rax+12]
	mov	DWORD PTR file$[rsp+40], eax

; 166  : 	file.current = ufile->start_cluster;

	mov	rax, QWORD PTR ufile$[rsp]
	mov	eax, DWORD PTR [rax+16]
	mov	DWORD PTR file$[rsp+44], eax

; 167  : 	file.flags = ufile->flags;

	mov	rax, QWORD PTR ufile$[rsp]
	movzx	eax, BYTE PTR [rax+20]
	mov	BYTE PTR file$[rsp+48], al

; 168  : 	file.status = ufile->status;

	mov	rax, QWORD PTR ufile$[rsp]
	movzx	eax, BYTE PTR [rax+24]
	mov	BYTE PTR file$[rsp+49], al

; 169  : 	file.open = 0;

	mov	QWORD PTR file$[rsp+64], 0

; 170  : 	file.read = 0;

	mov	QWORD PTR file$[rsp+72], 0

; 171  : 	file.read_blk = 0;

	mov	QWORD PTR file$[rsp+88], 0

; 172  : 	file.write = 0;

	mov	QWORD PTR file$[rsp+80], 0

; 173  : 	file.ioquery  = 0;

	mov	QWORD PTR file$[rsp+96], 0

; 174  : 
; 175  : 	vfs_node_t *node = get_current_thread()->fd[fd];

	call	get_current_thread
	movsxd	rcx, DWORD PTR fd$[rsp]
	mov	rax, QWORD PTR [rax+rcx*8+776]
	mov	QWORD PTR node$[rsp], rax

; 176  : 	if (node == NULL) {

	cmp	QWORD PTR node$[rsp], 0
	jne	SHORT $LN3@sys_write_

; 177  : 		return;

	jmp	SHORT $LN4@sys_write_
$LN3@sys_write_:

; 178  : 	}
; 179  : 
; 180  : 	if (ufile->flags) {

	mov	rax, QWORD PTR ufile$[rsp]
	cmp	DWORD PTR [rax+20], 0
	je	SHORT $LN2@sys_write_

; 181  : 		writefs(node, &file,buffer,file.size);

	mov	r9d, DWORD PTR file$[rsp+32]
	mov	r8, QWORD PTR buffer$[rsp]
	lea	rdx, QWORD PTR file$[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	call	writefs

; 182  : 	}else {

	jmp	SHORT $LN1@sys_write_
$LN2@sys_write_:

; 183  : 		writefs(node, node, buffer,file.size);

	mov	r9d, DWORD PTR file$[rsp+32]
	mov	r8, QWORD PTR buffer$[rsp]
	mov	rdx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	call	writefs
$LN1@sys_write_:
$LN4@sys_write_:

; 184  : 	}
; 185  : }

	add	rsp, 168				; 000000a8H
	ret	0
?sys_write_file@@YAXHPEAEPEAU_file_@@@Z ENDP		; sys_write_file
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\xeneva\aurora\aurora\sysserv\sysfile.cpp
_TEXT	SEGMENT
i$1 = 32
node$ = 40
file$ = 48
buff$2 = 56
fd$ = 80
buffer$ = 88
ufile$ = 96
?sys_read_file@@YAXHPEAEPEAU_file_@@@Z PROC		; sys_read_file

; 116  : void sys_read_file (int fd, uint8_t* buffer, FILE *ufile) {

$LN12:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 72					; 00000048H

; 117  : 	x64_cli ();

	call	x64_cli

; 118  : 	vfs_node_t *file = NULL; 

	mov	QWORD PTR file$[rsp], 0

; 119  : 
; 120  : 	vfs_node_t *node = NULL;

	mov	QWORD PTR node$[rsp], 0

; 121  : 
; 122  : 	/* if UFILE->size is greater than 0, it's a
; 123  : 	 * file system based file descriptor, so get
; 124  : 	 * the root file system file */
; 125  : 	if (ufile->size > 0){

	mov	rax, QWORD PTR ufile$[rsp]
	cmp	DWORD PTR [rax+4], 0
	jbe	$LN9@sys_read_f

; 126  : 		node = vfs_finddir("/");

	lea	rcx, OFFSET FLAT:$SG3820
	call	?vfs_finddir@@YAPEAU_vfs_node_@@PEAD@Z	; vfs_finddir
	mov	QWORD PTR node$[rsp], rax

; 127  : 		file = get_current_thread()->fd[fd];

	call	get_current_thread
	movsxd	rcx, DWORD PTR fd$[rsp]
	mov	rax, QWORD PTR [rax+rcx*8+776]
	mov	QWORD PTR file$[rsp], rax

; 128  : 		if (node == NULL)

	cmp	QWORD PTR node$[rsp], 0
	jne	SHORT $LN8@sys_read_f

; 129  : 			return;

	jmp	$LN10@sys_read_f
$LN8@sys_read_f:

; 130  : 		for (int i=0; i < file->size; i++){

	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN7@sys_read_f
$LN6@sys_read_f:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN7@sys_read_f:
	mov	rax, QWORD PTR file$[rsp]
	mov	eax, DWORD PTR [rax+32]
	cmp	DWORD PTR i$1[rsp], eax
	jae	$LN5@sys_read_f

; 131  : 			if (file->eof)

	mov	rax, QWORD PTR file$[rsp]
	movzx	eax, BYTE PTR [rax+36]
	test	eax, eax
	je	SHORT $LN4@sys_read_f

; 132  : 				break;

	jmp	SHORT $LN5@sys_read_f
$LN4@sys_read_f:

; 133  : 			uint64_t* buff = (uint64_t*)p2v((size_t)AuPmmngrAlloc());

	call	AuPmmngrAlloc
	mov	rcx, rax
	call	p2v
	mov	QWORD PTR buff$2[rsp], rax

; 134  : 			memset(buff, 0, 4096);

	mov	r8d, 4096				; 00001000H
	xor	edx, edx
	mov	rcx, QWORD PTR buff$2[rsp]
	call	memset

; 135  : 			readfs_block (node,file,(uint64_t*)v2p((size_t)buff));

	mov	rcx, QWORD PTR buff$2[rsp]
	call	v2p
	mov	r8, rax
	mov	rdx, QWORD PTR file$[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	call	readfs_block

; 136  : 			memcpy (buffer,buff,4096);

	mov	r8d, 4096				; 00001000H
	mov	rdx, QWORD PTR buff$2[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	call	memcpy

; 137  : 			buffer += 4096;

	mov	rax, QWORD PTR buffer$[rsp]
	add	rax, 4096				; 00001000H
	mov	QWORD PTR buffer$[rsp], rax

; 138  : 			AuPmmngrFree((void*)v2p((size_t)buff));

	mov	rcx, QWORD PTR buff$2[rsp]
	call	v2p
	mov	rcx, rax
	call	AuPmmngrFree

; 139  : 		}

	jmp	$LN6@sys_read_f
$LN5@sys_read_f:
	jmp	SHORT $LN3@sys_read_f
$LN9@sys_read_f:

; 140  : 
; 141  : 	}else if (ufile == NULL) {

	cmp	QWORD PTR ufile$[rsp], 0
	jne	SHORT $LN2@sys_read_f

; 142  : 		/* So this fd is non-file system based fd
; 143  : 		 * get it from fd table */
; 144  : 		node = get_current_thread()->fd[fd];

	call	get_current_thread
	movsxd	rcx, DWORD PTR fd$[rsp]
	mov	rax, QWORD PTR [rax+rcx*8+776]
	mov	QWORD PTR node$[rsp], rax

; 145  : 		if (node == NULL)

	cmp	QWORD PTR node$[rsp], 0
	jne	SHORT $LN1@sys_read_f

; 146  : 			return;

	jmp	SHORT $LN10@sys_read_f
$LN1@sys_read_f:

; 147  : 
; 148  : 		readfs(node, node, (uint64_t*)buffer, file->size);

	mov	rax, QWORD PTR file$[rsp]
	mov	r9d, DWORD PTR [rax+32]
	mov	r8, QWORD PTR buffer$[rsp]
	mov	rdx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	call	readfs
$LN2@sys_read_f:
$LN3@sys_read_f:
$LN10@sys_read_f:

; 149  : 	}
; 150  : 
; 151  : }

	add	rsp, 72					; 00000048H
	ret	0
?sys_read_file@@YAXHPEAEPEAU_file_@@@Z ENDP		; sys_read_file
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\xeneva\aurora\aurora\sysserv\sysfile.cpp
_TEXT	SEGMENT
fd_found$ = 32
i$ = 36
i$1 = 40
fd$ = 44
p$ = 48
node$ = 56
tv169 = 64
file_$2 = 72
tv184 = 80
tv173 = 88
tv158 = 96
_node$3 = 104
pathname$ = 112
file$4 = 128
$T5 = 240
$T6 = 344
filename$ = 480
ufile$ = 488
?sys_open_file@@YAHPEADPEAU_file_@@@Z PROC		; sys_open_file

; 49   : int sys_open_file (char* filename, FILE *ufile) {

$LN18:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rsi
	push	rdi
	sub	rsp, 456				; 000001c8H

; 50   : 	x64_cli();

	call	x64_cli

; 51   : 	char* p = strchr (filename, '/');

	mov	edx, 47					; 0000002fH
	mov	rcx, QWORD PTR filename$[rsp]
	call	strchr
	mov	QWORD PTR p$[rsp], rax

; 52   : 	if (p)

	cmp	QWORD PTR p$[rsp], 0
	je	SHORT $LN15@sys_open_f

; 53   : 		p++;

	mov	rax, QWORD PTR p$[rsp]
	inc	rax
	mov	QWORD PTR p$[rsp], rax
$LN15@sys_open_f:

; 54   : 
; 55   : 
; 56   : 	char pathname[16];
; 57   : 	int i;
; 58   : 	for (i = 0; i < 16; i++) {

	mov	DWORD PTR i$[rsp], 0
	jmp	SHORT $LN14@sys_open_f
$LN13@sys_open_f:
	mov	eax, DWORD PTR i$[rsp]
	inc	eax
	mov	DWORD PTR i$[rsp], eax
$LN14@sys_open_f:
	cmp	DWORD PTR i$[rsp], 16
	jge	SHORT $LN12@sys_open_f

; 59   : 		if ( p[i] == '/'  || p[i] == '\0')

	movsxd	rax, DWORD PTR i$[rsp]
	mov	rcx, QWORD PTR p$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 47					; 0000002fH
	je	SHORT $LN10@sys_open_f
	movsxd	rax, DWORD PTR i$[rsp]
	mov	rcx, QWORD PTR p$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	jne	SHORT $LN11@sys_open_f
$LN10@sys_open_f:

; 60   : 			break;

	jmp	SHORT $LN12@sys_open_f
$LN11@sys_open_f:

; 61   : 		pathname[i] = p[i];

	movsxd	rax, DWORD PTR i$[rsp]
	movsxd	rcx, DWORD PTR i$[rsp]
	mov	rdx, QWORD PTR p$[rsp]
	movzx	eax, BYTE PTR [rdx+rax]
	mov	BYTE PTR pathname$[rsp+rcx], al

; 62   : 	}

	jmp	SHORT $LN13@sys_open_f
$LN12@sys_open_f:

; 63   : 
; 64   : 	pathname[i] = 0;

	movsxd	rax, DWORD PTR i$[rsp]
	mov	BYTE PTR pathname$[rsp+rax], 0

; 65   : 
; 66   :     int fd = 0;

	mov	DWORD PTR fd$[rsp], 0

; 67   : 	vfs_node_t *node = vfs_finddir(filename);

	mov	rcx, QWORD PTR filename$[rsp]
	call	?vfs_finddir@@YAPEAU_vfs_node_@@PEAD@Z	; vfs_finddir
	mov	QWORD PTR node$[rsp], rax

; 68   : 
; 69   : 	bool fd_found = false;

	mov	BYTE PTR fd_found$[rsp], 0

; 70   : 	if (node) {

	cmp	QWORD PTR node$[rsp], 0
	je	SHORT $LN9@sys_open_f

; 71   : 		for (int i = 0; i < 60; i++) {

	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN8@sys_open_f
$LN7@sys_open_f:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN8@sys_open_f:
	cmp	DWORD PTR i$1[rsp], 60			; 0000003cH
	jge	SHORT $LN6@sys_open_f

; 72   : 			vfs_node_t *_node = get_current_thread()->fd[i];

	call	get_current_thread
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rax, QWORD PTR [rax+rcx*8+776]
	mov	QWORD PTR _node$3[rsp], rax

; 73   : 			if (_node == node) {

	mov	rax, QWORD PTR node$[rsp]
	cmp	QWORD PTR _node$3[rsp], rax
	jne	SHORT $LN5@sys_open_f

; 74   : 				fd = i;

	mov	eax, DWORD PTR i$1[rsp]
	mov	DWORD PTR fd$[rsp], eax

; 75   : 				fd_found = true;

	mov	BYTE PTR fd_found$[rsp], 1

; 76   : 				break;

	jmp	SHORT $LN6@sys_open_f
$LN5@sys_open_f:

; 77   : 			}
; 78   : 		}

	jmp	SHORT $LN7@sys_open_f
$LN6@sys_open_f:
$LN9@sys_open_f:

; 79   : 	}
; 80   : 
; 81   : 	if (!(strcmp(pathname, "dev") == 0)) {

	lea	rdx, OFFSET FLAT:$SG3802
	lea	rcx, QWORD PTR pathname$[rsp]
	call	strcmp
	test	eax, eax
	je	$LN4@sys_open_f

; 82   : 		vfs_node_t file = openfs(node, filename);

	mov	r8, QWORD PTR filename$[rsp]
	mov	rdx, QWORD PTR node$[rsp]
	lea	rcx, QWORD PTR $T6[rsp]
	call	openfs
	lea	rcx, QWORD PTR $T5[rsp]
	mov	rdi, rcx
	mov	rsi, rax
	mov	ecx, 104				; 00000068H
	rep movsb
	lea	rax, QWORD PTR file$4[rsp]
	lea	rcx, QWORD PTR $T5[rsp]
	mov	rdi, rax
	mov	rsi, rcx
	mov	ecx, 104				; 00000068H
	rep movsb

; 83   : 		if (ufile) {

	cmp	QWORD PTR ufile$[rsp], 0
	je	SHORT $LN3@sys_open_f

; 84   : 			ufile->id = fd;

	mov	rax, QWORD PTR ufile$[rsp]
	mov	ecx, DWORD PTR fd$[rsp]
	mov	DWORD PTR [rax], ecx

; 85   : 			ufile->size = file.size;

	mov	rax, QWORD PTR ufile$[rsp]
	mov	ecx, DWORD PTR file$4[rsp+32]
	mov	DWORD PTR [rax+4], ecx

; 86   : 			ufile->eof = file.eof;

	movzx	eax, BYTE PTR file$4[rsp+36]
	mov	rcx, QWORD PTR ufile$[rsp]
	mov	DWORD PTR [rcx+8], eax

; 87   : 			ufile->pos = file.pos;

	mov	rax, QWORD PTR ufile$[rsp]
	mov	ecx, DWORD PTR file$4[rsp+40]
	mov	DWORD PTR [rax+12], ecx

; 88   : 			ufile->start_cluster = file.current;

	mov	rax, QWORD PTR ufile$[rsp]
	mov	ecx, DWORD PTR file$4[rsp+44]
	mov	DWORD PTR [rax+16], ecx

; 89   : 			ufile->flags = file.flags; 

	movzx	eax, BYTE PTR file$4[rsp+48]
	mov	rcx, QWORD PTR ufile$[rsp]
	mov	DWORD PTR [rcx+20], eax

; 90   : 			ufile->status = file.status;

	movzx	eax, BYTE PTR file$4[rsp+49]
	mov	rcx, QWORD PTR ufile$[rsp]
	mov	DWORD PTR [rcx+24], eax
$LN3@sys_open_f:

; 91   : 		}
; 92   : 
; 93   : 		vfs_node_t *file_ = (vfs_node_t*)malloc(sizeof(vfs_node_t));

	mov	ecx, 104				; 00000068H
	call	malloc
	mov	QWORD PTR file_$2[rsp], rax

; 94   : 		memcpy(file_, &file, sizeof(vfs_node_t));

	mov	r8d, 104				; 00000068H
	lea	rdx, QWORD PTR file$4[rsp]
	mov	rcx, QWORD PTR file_$2[rsp]
	call	memcpy

; 95   : 		get_current_thread()->fd[get_current_thread()->fd_current] = file_;

	call	get_current_thread
	mov	QWORD PTR tv158[rsp], rax
	call	get_current_thread
	movsxd	rax, DWORD PTR [rax+1256]
	mov	rcx, QWORD PTR file_$2[rsp]
	mov	rdx, QWORD PTR tv158[rsp]
	mov	QWORD PTR [rdx+rax*8+776], rcx

; 96   : 		fd = get_current_thread()->fd_current;

	call	get_current_thread
	mov	eax, DWORD PTR [rax+1256]
	mov	DWORD PTR fd$[rsp], eax

; 97   : 		get_current_thread()->fd_current++;

	call	get_current_thread
	add	rax, 1256				; 000004e8H
	mov	QWORD PTR tv169[rsp], rax
	mov	rax, QWORD PTR tv169[rsp]
	mov	eax, DWORD PTR [rax]
	inc	eax
	mov	rcx, QWORD PTR tv169[rsp]
	mov	DWORD PTR [rcx], eax

; 98   : 	}else {

	jmp	SHORT $LN2@sys_open_f
$LN4@sys_open_f:

; 99   : 		if (!fd_found){

	movzx	eax, BYTE PTR fd_found$[rsp]
	test	eax, eax
	jne	SHORT $LN1@sys_open_f

; 100  : 			get_current_thread()->fd[get_current_thread()->fd_current] = node;

	call	get_current_thread
	mov	QWORD PTR tv173[rsp], rax
	call	get_current_thread
	movsxd	rax, DWORD PTR [rax+1256]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rdx, QWORD PTR tv173[rsp]
	mov	QWORD PTR [rdx+rax*8+776], rcx

; 101  : 			fd = get_current_thread()->fd_current;

	call	get_current_thread
	mov	eax, DWORD PTR [rax+1256]
	mov	DWORD PTR fd$[rsp], eax

; 102  : 			get_current_thread()->fd_current++;

	call	get_current_thread
	add	rax, 1256				; 000004e8H
	mov	QWORD PTR tv184[rsp], rax
	mov	rax, QWORD PTR tv184[rsp]
	mov	eax, DWORD PTR [rax]
	inc	eax
	mov	rcx, QWORD PTR tv184[rsp]
	mov	DWORD PTR [rcx], eax
$LN1@sys_open_f:
$LN2@sys_open_f:

; 103  : 		}
; 104  : 	}
; 105  : 	
; 106  : 	//! return the allocated fd number
; 107  : 	return fd;

	mov	eax, DWORD PTR fd$[rsp]

; 108  : }

	add	rsp, 456				; 000001c8H
	pop	rdi
	pop	rsi
	ret	0
?sys_open_file@@YAHPEADPEAU_file_@@@Z ENDP		; sys_open_file
_TEXT	ENDS
END
