; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG3086	DB	'uthread', 00H
CONST	ENDS
PUBLIC	?get_thread_id@@YAGXZ				; get_thread_id
PUBLIC	?create_uthread@@YAXP6AXPEAX@Z@Z		; create_uthread
EXTRN	?pmmngr_alloc@@YAPEAXXZ:PROC			; pmmngr_alloc
EXTRN	x64_cli:PROC
EXTRN	x64_read_cr3:PROC
EXTRN	?create_user_thread@@YAPEAU_thread_@@P6AXPEAX@Z_K2QEADE@Z:PROC ; create_user_thread
EXTRN	?get_current_thread@@YAPEAU_thread_@@XZ:PROC	; get_current_thread
pdata	SEGMENT
$pdata$?get_thread_id@@YAGXZ DD imagerel $LN3
	DD	imagerel $LN3+26
	DD	imagerel $unwind$?get_thread_id@@YAGXZ
$pdata$?create_uthread@@YAXP6AXPEAX@Z@Z DD imagerel $LN3
	DD	imagerel $LN3+67
	DD	imagerel $unwind$?create_uthread@@YAXP6AXPEAX@Z@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?get_thread_id@@YAGXZ DD 010401H
	DD	04204H
$unwind$?create_uthread@@YAXP6AXPEAX@Z@Z DD 010901H
	DD	08209H
xdata	ENDS
; Function compile flags: /Odtp
; File e:\xeneva project\xeneva\aurora\aurora\sysserv\systhread.cpp
_TEXT	SEGMENT
tv67 = 48
entry$ = 80
?create_uthread@@YAXP6AXPEAX@Z@Z PROC			; create_uthread

; 20   : void create_uthread (void (*entry) (void*)) {

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 21   : 	x64_cli ();

	call	x64_cli

; 22   : 	create_user_thread (entry,(uint64_t)pmmngr_alloc(),x64_read_cr3(),"uthread",1);

	call	x64_read_cr3
	mov	QWORD PTR tv67[rsp], rax
	call	?pmmngr_alloc@@YAPEAXXZ			; pmmngr_alloc
	mov	BYTE PTR [rsp+32], 1
	lea	r9, OFFSET FLAT:$SG3086
	mov	rcx, QWORD PTR tv67[rsp]
	mov	r8, rcx
	mov	rdx, rax
	mov	rcx, QWORD PTR entry$[rsp]
	call	?create_user_thread@@YAPEAU_thread_@@P6AXPEAX@Z_K2QEADE@Z ; create_user_thread

; 23   : }

	add	rsp, 72					; 00000048H
	ret	0
?create_uthread@@YAXP6AXPEAX@Z@Z ENDP			; create_uthread
_TEXT	ENDS
; Function compile flags: /Odtp
; File e:\xeneva project\xeneva\aurora\aurora\sysserv\systhread.cpp
_TEXT	SEGMENT
?get_thread_id@@YAGXZ PROC				; get_thread_id

; 14   : uint16_t get_thread_id () {

$LN3:
	sub	rsp, 40					; 00000028H

; 15   : 	x64_cli ();

	call	x64_cli

; 16   : 	return get_current_thread()->id;

	call	?get_current_thread@@YAPEAU_thread_@@XZ	; get_current_thread
	movzx	eax, WORD PTR [rax+226]

; 17   : }

	add	rsp, 40					; 00000028H
	ret	0
?get_thread_id@@YAGXZ ENDP				; get_thread_id
_TEXT	ENDS
END
